name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Debug secrets
        run: echo "GISTRESUME=${{ secrets.GISTRESUME }}"
      
      - name: Replace environment variable
        run: |
          sed -i 's|gistResumeUrl: ""|gistResumeUrl: "'${{ secrets.GISTRESUME }}'"|' src/environments/environment.prod.ts


      - name: Build Angular app
        run: |
          echo "GISTRESUME=$GISTRESUME" > .env
          npm run build --prod
        env:
          GISTRESUME: ${{ secrets.GISTRESUME }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/browser